# short name and type dict according to 'application_type'
#
# Haven't used any more exotic Tradfri devices... will add more
# as they are encounterd, tested or suggested
#
0:
  name: 'TRADFRI remote control'
  type: 'remote'
2:
  name: 'TRADFRI bulb'
  type: 'bulb'
3:
  name: 'TRADFRI outlet'
  type: 'outlet'
4:
  name: 'TRADFRI motion sensor'
  type: 'motion'
#
# 7: type: 'blind'
# 10: type 'airpurifier
# more info
# https://github.com/vwout/vera-tradfri/blob/master/L_TradfriGW.lua#L51
