# security code on the back of the Tradfri
# Used to generate psk (pre-shared key) for authentication
tradfri_security_code: '123abc456DEF789ghi'
# locactions of the psk
tradfri_standalone_psk_conf: 'tradfri_standalone_psk.conf' #not used/implemented yet

# use zabbix config from host /etc/zabbix/zabbix_agentd.conf (ServerActive=...)
# zabbix-server need to allow zabbix trap connections)
zabbix_sender_settings: 'use_config=True'
#ZabbixSender('use_config=True')
#ZabbixSender('hostname')
#ZabbixSender('IP ADDRESS')

# needs to be same as 'Host name' configured in Zabbix front end
monitored_hostname: 'tradfri.local'

# testing / debugging variables
print_zabbix_send: false
do_zabbix_send: true
do_it_once: false
list_all_items: false
gateway_detailed_debug: false
